spring:
  profiles:
    active: ${COIN_BACKEND_ACTIVE_PROFILE:default}
  application:
    name: books
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL:jdbc:postgresql://localhost:5432/books}
    username: ${DB_USER:postgres}
    password: ${DB_PASS:1234}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:db/changelog/changelog.yaml
